import styles from "file://styles.css?minify";
import type { LunaUnload } from "@luna/core";
import { MediaItem, PlayState, StyleTag, observe } from "@luna/lib";
import { Settings } from "./SettingsPage";
import { settings } from "./settings";
export { Settings };
export const unloads = new Set<LunaUnload>();
new StyleTag("RoraTidalMv", unloads, styles);
const ROW = 'div[data-test="tracklist-row"], div[data-test="media-list-item"]';
const MARK = "data-rora-tidal-mv";
let dialog: HTMLDialogElement | null = null;
let pausedByUs = false;
type YtPlayer = { destroy: () => void; playVideo: () => void; pauseVideo: () => void; setVolume: (n: number) => void; setPlaybackQuality?: (q: string) => void };
let player: YtPlayer | null = null;
let apiPromise: Promise<void> | null = null;
const loadYouTubeApi = (): Promise<void> => apiPromise ??= new Promise((resolve) => { if ((window as any).YT?.Player) return resolve(); const script = document.createElement("script"); script.src = "https://www.youtube.com/iframe_api"; (window as any).onYouTubeIframeAPIReady = resolve; document.head.append(script); });
const esc = (s: string) => encodeURIComponent(s);
const current = async () => { const item = await MediaItem.fromPlaybackContext(); const track = item?.tidalItem ?? {}; return { title: String(track.title ?? ""), artist: String(track.artist?.name ?? track.artists?.[0]?.name ?? "") }; };
const findVideo = async (query: string): Promise<string | null> => { if (!settings.youtubeApiKey) return null; const r = await fetch(`https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=1&q=${esc(`${query} official music video`)}&key=${esc(settings.youtubeApiKey)}`); if (!r.ok) return null; const j = await r.json() as { items?: Array<{ id?: { videoId?: string } }> }; return j.items?.[0]?.id?.videoId ?? null; };
const close = () => { player?.destroy(); player = null; dialog?.remove(); dialog = null; if (pausedByUs && settings.resumeTidalOnClose) PlayState.play(); pausedByUs = false; };
const open = async () => { if (dialog) return; const { title, artist } = await current(); if (!title) return; if (PlayState.playing) { PlayState.pause(); pausedByUs = true; } const query = `${artist} ${title}`.trim(); const videoId = await findVideo(query); dialog = document.createElement("dialog"); dialog.className = "rora-mv-dialog"; dialog.innerHTML = `<div class="rora-mv-head"><strong>${query.replace(/[<&>]/g, "")}</strong><button class="rora-mv-close" aria-label="Close">×</button></div>`; if (videoId) { const iframe = document.createElement("iframe"); iframe.className = "rora-mv-frame"; iframe.src = `https://www.youtube.com/embed/${encodeURIComponent(videoId)}?enablejsapi=1&autoplay=1`; iframe.allow = "autoplay; encrypted-media; picture-in-picture"; iframe.allowFullscreen = true; dialog.append(iframe); } else { const box = document.createElement("div"); box.className = "rora-mv-search"; box.innerHTML = `<a target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${esc(`${query} official music video`)}">Search YouTube for this MV</a>`; dialog.append(box); } dialog.querySelector(".rora-mv-close")?.addEventListener("click", close); dialog.addEventListener("cancel", close); dialog.addEventListener("close", close, { once: true }); document.body.append(dialog); dialog.showModal(); };
const addButton = (row: HTMLElement) => {
 if (row.querySelector(`[${MARK}]`)) return;
 const actionHost = row.querySelector<HTMLElement>('[data-test="track-actions"], [data-test="media-item-actions"], [class*="action"]');
 const buttons = [...row.querySelectorAll<HTMLButtonElement>("button, [role=button]")].filter((button) => !button.closest(`[${MARK}]`));
 const fallback = buttons.at(-1)?.parentElement;
 const host = actionHost ?? fallback ?? row;
 const b = document.createElement("button"); b.type = "button"; b.setAttribute(MARK, ""); b.className = "rora-mv-button"; b.title = "Open music video"; b.setAttribute("aria-label", "Open music video"); b.textContent = "🎬";
 b.addEventListener("click", (e) => { e.stopPropagation(); void open(); });
 if (host === row) { row.style.position = row.style.position || "relative"; b.style.cssText = "position:absolute;right:8px;bottom:8px;z-index:2"; }
 host.insertBefore(b, host.firstElementChild ?? null);
};
document.querySelectorAll<HTMLElement>(ROW).forEach(addButton); observe<HTMLElement>(unloads, ROW, addButton);
const retryTimer = window.setInterval(() => document.querySelectorAll<HTMLElement>(ROW).forEach(addButton), 500);
unloads.add(() => window.clearInterval(retryTimer));
unloads.add(() => { close(); document.querySelectorAll(`[${MARK}]`).forEach((e) => e.remove()); });
